### ISSUE TITLE
Add OpenID Connect 

### ISSUE THREAD

**Issue by Aqua1507** [mynona/vapor-oauth-example#2]
Would be great to extend and support the OpenID connect!

**Comment by m-y-n-o-n-a** [comment]
Once it is implemented in the repository we can update the example.

**Comment by Aqua1507** [comment]
okay, sounds good! what about JWKS?

**Comment by mynona** [comment]
See first draft / but this is still work in progress on vamsii777 side and as I know you are also curious I share this early exploration with you. But there are still some issues that I discovered. Let's wait until vamsii makes a public release but you can check it out already if you are interested. What is missing is to validate the received tokens but the endpoint is already set up by vamsii777: .well-known/.well-known/jwks.json to retrieve the public rsa key



https://github.com/mynona/vapor-oauth-example/releases/tag/0.1.8
